### ISSUE TITLE
Software Station hangs when 'pkg update' is required

### ISSUE THREAD

**Issue by wb7odyfred** [ghostbsd/ghostbsd#12]
## Software Station hangs with 2 chars input into search window, when 'pkg update' is required

Here is example from a separate terminal window, executing the pkg search for mpv

will@will-ghostbsd-pc /u/h/will> `pkg search -Q name mpv`
pkg: Repository GhostBSD missing. 'pkg update' required
pkg: Repository GhostBSD cannot be opened. 'pkg update' required
[Software_Station_Hang_Issue.txt](https://github.com/ghostbsd/ghostbsd/files/5125155/Software_Station_Hang_Issue.txt)

After waiting some time, I issued a PS AX command  Tue Aug 25 09:52:22 PDT 2020

[Software_Station_Hang_Issue2.txt](https://github.com/ghostbsd/ghostbsd/files/5125193/Software_Station_Hang_Issue2.txt)

So maybe then it allowed me to type a couple more characters into the "input box field" in Software Station

**Comment by wb7odyfred** [comment]
Notes:   I have crappy slow error prone internet connection through a WIFI hotspot on my mobile phone.  So the <sudo pkg -d update  -f> process is not going well.   Will move computer to a better WIFI internet connection , like at a coffee shop.

 sudo pkg -d update -f
Password:
DBG(1)[22182]> pkg initialized
Updating GhostBSD repository catalogue...
DBG(1)[22182]> PkgRepo: verifying update for GhostBSD
DBG(1)[22182]> PkgRepo: need forced update of GhostBSD
DBG(1)[22182]> Pkgrepo, begin update of '/var/db/pkg/repo-GhostBSD.sqlite'
DBG(1)[22182]> Fetch: fetching from: http://pkg.us.ghostbsd.org/stable/FreeBSD:12:amd64/latest/meta.conf with opts "i"
DBG(1)[22182]> Fetch: fetching from: http://pkg.us.ghostbsd.org/stable/FreeBSD:12:amd64/latest/meta.conf with opts "i"
DBG(1)[22182]> Fetch: fetching from: http://pkg.us.ghostbsd.org/stable/FreeBSD:12:amd64/latest/meta.conf with opts "i"
DBG(1)[22182]> Fetch: fetching from: http://pkg.us.ghostbsd.org/stable/FreeBSD:12:amd64/latest/meta.txz with opts "i"
DBG(1)[22182]> Fetch: fetching from: http://pkg.us.ghostbsd.org/stable/FreeBSD:12:amd64/latest/meta.txz with opts "i"
DBG(1)[22182]> Fetch: fetching from: http://pkg.us.ghostbsd.org/stable/FreeBSD:12:amd64/latest/meta.txz with opts "i"
pkg: http://pkg.us.ghostbsd.org/stable/FreeBSD:12:amd64/latest/meta.txz: Operation timed out
repository GhostBSD has no meta file, using default settings
DBG(1)[22182]> Fetch: fetching from: http://pkg.us.ghostbsd.org/stable/FreeBSD:12:amd64/latest/packagesite.txz with opts "i"
DBG(1)[22182]> Fetch: fetching from: http://pkg.us.ghostbsd.org/stable/FreeBSD:12:amd64/latest/packagesite.txz with opts "i"
DBG(1)[22182]> Fetch: fetching from: http://pkg.us.ghostbsd.org/stable/FreeBSD:12:amd64/latest/packagesite.txz with opts "i"
pkg: http://pkg.us.ghostbsd.org/stable/FreeBSD:12:amd64/latest/packagesite.txz: Operation timed out
Unable to update repository GhostBSD
Error updating repositories!

So I will try again, using a better wifi internet connection.  Then report back success.

**Comment by maxsteciuk** [comment]
Hello,
The same happens for me as well. The package repository server doesn't appear to be pingable.

```sudo pkg -d update
```DBG(1)[18328]> pkg initialized
```Updating GhostBSD repository catalogue...
```DBG(1)[18328]> PkgRepo: verifying update for GhostBSD
```DBG(1)[18328]> PkgRepo: need forced update of GhostBSD
```DBG(1)[18328]> Pkgrepo, begin update of '/var/db/pkg/repo-GhostBSD.sqlite'
```DBG(1)[18328]> Fetch: fetching from: http://pkg.us.ghostbsd.org/stable/FreeBSD:12:amd64/latest/meta.conf with opts "i"
^C
``` ping pkg.us.ghostbsd.org
```PING pkg.us.ghostbsd.org (64.182.177.161): 56 data bytes

**Comment by ericbsd** [comment]
I confirm the server is down I am trying to get Nextarrey to fix the issue.

**Comment by ericbsd** [comment]
Sever should be back now.
