### ISSUE TITLE
Package or Kernel Missmatch

### ISSUE THREAD

**Issue by keypunch416** [ghostbsd/ghostbsd#27]
GhostBSD-20.08.04-XFCE.iso:

ghostbsd@livecd ~> pkg update
pkg: Insufficient privileges to update the repository catalogue.
ghostbsd@livecd ~ [77]> 
ghostbsd@livecd ~ [77]> sudo pkg update
Updating GhostBSD repository catalogue...
Fetching meta.conf: 100%    163 B   0.2kB/s    00:01    
Fetching packagesite.txz: 100%    6 MiB   1.7MB/s    00:04    
Processing entries:   0%
Newer FreeBSD version for package roundcube-veximaccountadmin-php74:
To ignore this error set IGNORE_OSVERSION=yes
- package: 1202502
- running kernel: 1201519
Ignore the mismatch and continue? [Y/n]: y
Processing entries: 100%
GhostBSD repository update completed. 32896 packages processed.
All repositories are up to date.
ghostbsd@livecd ~>

**Comment by ericbsd** [comment]
Not a bug. Just do a sudo pkg upgrade -fy.

**Comment by keypunch416** [comment]
sudo pkg upgrade -fy. fails as noted in issue #28.

**Comment by keypunch416** [comment]
Closing as per issue #28 reasons.
