### ISSUE TITLE
Unable to install package with PKG due to read only file system

### ISSUE THREAD

**Issue by keypunch416** [ghostbsd/ghostbsd#28]
GhostBSD-20.08.04-XFCE.iso:

ghostbsd@livecd ~ [127]> sudo pkg install htop
Updating GhostBSD repository catalogue...
GhostBSD repository is up to date.
All repositories are up to date.
New version of pkg detected; it needs to be installed first.
The following 1 package(s) will be affected (of 0 checked):

Installed packages to be UPGRADED:
	pkg: 1.14.6 -> 1.15.10 [GhostBSD]

Number of packages to be upgraded: 1

7 MiB to be downloaded.

Proceed with this action? [y/N]: y
[1/1] Fetching pkg-1.15.10.txz: 100%    7 MiB   1.5MB/s    00:05    
Checking integrity... done (0 conflicting)
[1/1] Upgrading pkg from 1.14.6 to 1.15.10...
[1/1] Extracting pkg-1.15.10:   0%
pkg: Fail to create /usr/local/share/licenses/pkg-1.15.10:Read-only file system
[1/1] Extracting pkg-1.15.10: 100%
ghostbsd@livecd ~ [3]> sudo pkg install htop
Updating GhostBSD repository catalogue...
GhostBSD repository is up to date.
All repositories are up to date.
New version of pkg detected; it needs to be installed first.
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

Installed packages to be UPGRADED:
	pkg: 1.14.6 -> 1.15.10 [GhostBSD]

Number of packages to be upgraded: 1

Proceed with this action? [y/N]: y
[1/1] Upgrading pkg from 1.14.6 to 1.15.10...
[1/1] Extracting pkg-1.15.10:   0%
pkg: Fail to create /usr/local/share/licenses/pkg-1.15.10:Read-only file system
[1/1] Extracting pkg-1.15.10: 100%
ghostbsd@livecd ~ [3]>

**Comment by keypunch416** [comment]
sudo pkg upgrade -fy still fails as previously noted had tried.

**Comment by ericbsd** [comment]
Are you trying to do that on the live drive?

**Comment by keypunch416** [comment]
Yes.  Why I used the .iso in image name as opposed to not and never stated was installed as was not.  I assume the livecd user does not exist in the installed instance, but do not know.

**Comment by ericbsd** [comment]
GhostBSD 20.08.04 live system is not RW. You will have to try the last new developments iso which is RW using ZFS.

**Comment by keypunch416** [comment]
Sadly ZFS is approach is not what I would want in a Live based image.  The appropriate Live image approach is not ZFS in my opinion.  So sad, have to stay with Linux based Live systems that are well.... lets just say challenged live or installed.  Amazing OliveBSD could do what cannot be done years later with BSDs.  Time to revert to the very inferior Linux Kernel based Live (and is likewise inferior installed system)
