### ISSUE TITLE
Site wiki error in link

### ISSUE THREAD

**Issue by cpeticus** [ghostbsd/ghostbsd#3]
Link http://ghostbsd.org/contribute#document
Shows a blue button that says Wiki
Clicking said button directs to other link:
http://wiki.ghostbsd.org/wiki/index.php/Main_Page

which gives an error the correct link is:
https://wiki.ghostbsd.org/index.php/Main_Page

**Comment by ericbsd** [comment]
Thanks for reporting this, I have fixed that.
