### ISSUE TITLE
size display

### ISSUE THREAD

**Issue by valognes** [ghostbsd/ghostbsd#31]
I tried ghostbsd 2 years a go and everything was fine. I replaced it by archlinux for a year. Yesterday i wanted to install ghostbsd again but the screen diplay is not on the right size and the video card fan is fast. The video card is a Radeo r7 and I can't get the right driver anymore. Thank you

**Comment by ericbsd** [comment]
If you need help, yep or it is supposed to be a bug report?

**Comment by valognes** [comment]
I have a laptop HP pavillon with radeo r7.  I'm not able to get a right screen display. I need ''Display: x11 server: X.Org 1.20.4 driver: amdgpu,ati unloaded: fbdev,modesetting,vesa  resolution: 1366x768~60Hz .  I'm not able to get the driver from the depot. I have only 600x800 for resolution.  I hope, It's clear, I'm french. thank you

**Comment by ericbsd** [comment]
This is for bugs and not for questions if you need help please use discussions, Telegram or the forums.
