### ISSUE TITLE
GhostBSD-20.11.28 Installer Crashes

### ISSUE THREAD

**Issue by salman258746** [ghostbsd/ghostbsd#33]
I am trying to install GhostBSD-20.11.28 in VirtualBox (under Arch Linux). Following system specifications are set in VirtualBox:
```
System Profile: FreeBSD (64Bit)
Processors: 2 Cores
Hard Disk: 30 GB
RAM: 4 GB
Video Memory: 128 MB
Graphics Controller: VMSVGA
```
I have selected selected following options during installation:
```
UFS Full Disk Configuraton
SWAP: 2048 MB
Partition Table: MBR
```
However, the installer crashes every time.
**Please check this screenshot:**

![ghost-crash](https://user-images.githubusercontent.com/77200681/104094848-4c718b80-52b5-11eb-86f9-29d1e6c04ef3.png)

**And following log file:**
[pc-sysinstall.log](https://github.com/ghostbsd/ghostbsd/files/5791280/pc-sysinstall.log)

Kindly look into it.
Regards

**Comment by ericbsd** [comment]
Did you read the download page?

you run out of ram. you need about 5 GB with the new live cd that is why the recommendation on the download page is 6GB of ram.

I am working on lowering the ram usage by the installer.

**Comment by salman258746** [comment]
Thanks for clarification.
Kindly also look into the message given by installer. If memory is set below 4 GB then it says that minimum 4 GB is required. I think this message also needs to be updated.

![installer](https://user-images.githubusercontent.com/77200681/104100161-da9e3f80-52be-11eb-8fdf-2e0428019583.png)

**Comment by ericbsd** [comment]
That was not updated from the FuryBSD code.

**Comment by ericbsd** [comment]
The latest builds contain improvement on the memory size https://www.ghostbsd.org/download#latest_builds. These iso's should install on a 4GB system.

**Comment by salman258746** [comment]
I increased the RAM to 5 GB during installation and then decreased to 4 GB again (after installation). GhostBSD is an excellent OS. Well done Eric :-)
