### ISSUE TITLE
application hw-probe installed in Live version of GhostBSD.iso

### ISSUE THREAD

**Issue by wb7odyfred** [ghostbsd/ghostbsd#35]
[https://bsd-hardware.info/index.php?view=howto](https://bsd-hardware.info/index.php?view=howto)
[Github Howto for FreeBSD](https://github.com/linuxhw/hw-probe/blob/master/INSTALL.BSD.md)

[NomadBSD.org](https://nomadbsd.org) has this command available to create a hardware probe to identify all the hardware in the computer.

Maybe we can add hw-probe to the file system in the Live image GhostBSD for users to identify which wifi devices are supported with BSD drivers and which are not.

[Linux-hardware.org](https://Linux-hardware.org) is the equivalent Linux version of hw-probe application

Here is a file I made while installing hw-probe app to a clean GhostBSD install.   This should show the other packages that need to be installed.
[hw-probe_install.txt](https://github.com/ghostbsd/ghostbsd/files/5813680/hw-probe_install.txt)

**Comment by ericbsd** [comment]
Duplicate https://github.com/ghostbsd/ghostbsd-build/issues/128
