### ISSUE TITLE
Graphics Problem after update to 20.04

### ISSUE THREAD

**Issue by qubit72** [ghostbsd/ghostbsd#4]
After successful `sudo pkg update -f && sudo pkg upgrade` my PC hangs suddenly at next reboot.

![IMAG1781_](https://user-images.githubusercontent.com/61522465/80814737-b1280280-8bcc-11ea-803e-b57e0402b087.jpg)

Single user mode is still possible, so i removed `xf86-video-ati` and `drm-kmod` and commented out 
`# kld_list="/boot/modules/radeonkms.ko"` in my rc.conf. 

Now its possible to boot into Mate-Desktop, but it is impossible to set the right display resolution (1680x1050). I stuck at 1400x1050.

`pciconf -vl` shows:

`vgapci0@pci0:1:0:0:	class=0x030000 card=0xe113174b chip=0x954f1002 rev=0x00 hdr=0x00
    vendor     = 'Advanced Micro Devices, Inc. [AMD/ATI]'
    device     = 'RV710 [Radeon HD 4350/4550]'
    class      = display
    subclass   = VGA`

`uname -U` shows 1201513.

No Updates available with `sudo pkg update -f && sudo pkg upgrade`.

**Comment by ericbsd** [comment]
Doing `sudo pkg update -f && sudo pkg upgrade` it is bad for upgrading OS you need to do force upgrade on os upgrade.

`sudo pkg update -f && sudo pkg upgrade -f`

We recommend to use the graphical update manager since it does the  pkg upgrade -f when OS upgrade are available.

**Comment by ericbsd** [comment]
modsetting needs to be in xorg.conf instead of amdgpu driver

**Comment by ericbsd** [comment]
Also, the release announcement was specifying to use pkg upgrade -f.

To upgrade if not done already:
uname -U should output 1201513

sudo pkg update -f
sudo pkg upgrade -f

Note: If you do your packages upgrade with pkg or Update Station, you are up to date.

**Comment by ericbsd** [comment]
On the boot loader menu try option 2. Disable syscons for AMD.

**Comment by qubit72** [comment]
Hi Eric, 
thank you very much for your fast reply. 
I'm quite a BSD Newbie (since GhostBSD 20.01), but love it an try to learn...
Actually doing a `sudo pkg update -f && sudo pkg upgrade -f` and the number of packages to be reinstalled is 726. This will take some time... 
I have tried boot loader menu option 2 yesterday with no success. But I have learned a lot about single user mode. :-)
I will report the outcome of my upgrade. I`m sorry if it`s simply my fault doing the upgrade the wrong way. 
Best regards!
qubit72

**Comment by qubit72** [comment]
Installed `drm-kmod` and `xf86-video-ati` again, readded `/boot/modules/radeonkms.ko` in my rc.conf and did the `sudo pkg update -f && sudo pkg upgrade -f`. After rebooting everything was fine, no boot problems and full display resolution 1680x1050.
Thanks a lot, Eric!  :+1: :+1: :+1:

**Comment by ericbsd** [comment]
My pleasure.
